omsa-admin/adminomsa/adminomsa/urls.py
from django.contrib import admin
from django.urls import path, include
from obra.urls import obra_patterns
from operario.urls import operario_patterns
from herramienta.urls import herramienta_patterns
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    # Paths de obras
    path('obra/', include(obra_patterns)),
    path('operario/', include(operario_patterns)),
    path('herramienta/', include(herramienta_patterns)),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

omsa-admin/adminomsa/core/urls.py
from django.urls import path
from .views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

omsa-admin/adminomsa/operario/urls.py
from django.urls import path
from .views import OperarioListView, OperarioUpdate, OperarioCreate, InactivoListView, DiaListView, DiaUpdate
operario_patterns = ([
    path('', OperarioListView.as_view(), name='operario'),
    path('fecha/', DiaListView.as_view(), name='fecha'),
    path('<slug>/', OperarioUpdate.as_view(), name='update'),
    path('new/create/', OperarioCreate.as_view(), name='create'),
    path('inactivo', InactivoListView.as_view(), name='inactivo'),
    path('fecha/<slug>/', DiaUpdate.as_view(), name='parte'),
], 'operario')

omsa-admin/adminomsa/obra/models.py
from django.db import models
from collections import Counter

# -----------------------------------------------------------------------------------------  Obra

def custom_upload_to(instance, filename):
    old_instance = Obra.objects.get(pk=instance.pk)
    old_instance.imagen.delete()
    return 'obra/' + filename

class Obra(models.Model):

    ESTADO_CHOISE = (
        ('Proxima', 'Proxima'),
        ('Ejecucion', 'Ejecucion'),
        ('Terminada', 'Terminada'),
    )

    obra = models.CharField(max_length=50)
    obra_id = models.CharField(max_length=4)
    pisos = models.IntegerField()
    posiciones = models.IntegerField()
    imagen = models.ImageField(upload_to=custom_upload_to, default='obra/avatar_b.jpg', null=True, blank=True)
    estado = models.CharField(max_length=50, choices=ESTADO_CHOISE)
    ingenieria_obra = models.FileField(null=True, blank=True)  # subir archivos PDF

    slug = models.SlugField(max_length=4) # Repetir ID

    class Meta:
        ordering = ['obra_id']

    def __str__(self):
         return self.obra


# -----------------------------------------------------------------------------------------  Modulos y monaje

class Modulo(models.Model):
    obra = models.ForeignKey(Obra, on_delete=models.PROTECT)
    modulo = models.CharField(max_length=50, null=True, blank=True)
    ingenieria_modulo = models.FileField(null=True, blank=True)  # subir archivos PDF 

    def __str__(self):
         return self.modulo

class Montaje(models.Model):
    piso = models.CharField(max_length=5,)
    posicion = models.IntegerField()
    modulo = models.ForeignKey(Modulo, on_delete=models.PROTECT)
    identificador = models.IntegerField(null=True, blank=True)
    estado = models.CharField(max_length=50, default='fabrica')
    fecha_montado = models.DateField(null=True, blank=True)
    fecha_recibido = models.DateField(null=True, blank=True)
    anclajes = models.BooleanField(default=False)
    sellados_int = models.BooleanField(default=False)
    lana = models.BooleanField(default=False)
    pintura = models.BooleanField(default=False)
    recibido = models.BooleanField(default=False)
    observaciones = models.TextField(max_length=50, null=True, blank=True)
    reposicion = models.BooleanField(default=False)
    reposicion_obs = models.CharField(max_length=30, null=True, blank=True)
    remito = models.IntegerField(null=True, blank=True)
    apto = models.BooleanField(default=True)
    date_modified = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = 'Montaje'
        ordering = ['id']

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        
        if self.recibido == False:
            self.estado = 'fabrica'
        if self.fecha_montado == None and self.recibido == True and self.apto == True:
            self.estado = 'recibido'
        if self.fecha_montado != None:
            self.estado = 'montado'
        if self.fecha_montado != None and self.lana == True and self.anclajes == True and self.pintura == True and self.sellados_int == True:
            self.estado = 'completo'
        if self.reposicion == True :
            self.estado = 'incompleto'
        if self.identificador == None and self.fecha_montado != None:
            self.estado = 'falta_id'
        if self.apto == False:
            self.estado = 'no_apto'
        super(Montaje, self).save(*args, **kwargs)

        identlist = list(Montaje.objects.filter(modulo__obra__obra_id=self.modulo.obra.obra_id).values_list('identificador', flat=True))
        d = Counter(identlist)
        dupes = list([item for item in d if d[item]>1])
        idlist = Montaje.objects.filter(modulo__obra__obra_id=self.modulo.obra.obra_id)
        for i in idlist.iterator():
            if i.identificador != None:
                if i.estado == 'repetido':
                    if i.recibido == False:
                        i.estado = 'fabrica'
                    if i.fecha_montado == None and i.recibido == True and i.apto == True:
                        i.estado = 'recibido'
                    if i.fecha_montado != None:
                        i.estado = 'montado'
                    if i.fecha_montado != None and i.lana == True and i.anclajes == True and i.pintura == True and i.sellados_int == True:
                        i.estado = 'completo'
                    if i.reposicion == True :
                      i.estado = 'incompleto'
                    if i.identificador == None and i.fecha_montado != None:
                        i.estado = 'falta_id'
                    if i.apto == False:
                        i.estado = 'no_apto'
                    super(Montaje, i).save(*args, **kwargs)         
                if i.identificador in dupes:
                    i.estado = 'repetido'
                    super(Montaje, i).save(*args, **kwargs)


                    
    # def get_absolute_url(self):
    #     return reverse('post-detail', kwargs={'pk': self.pk})

    # -----------------------------------------------------------------------------------------  Recepcion de modulos

omsa-admin/adminomsa/operario/forms.py
from django import forms
from .models import Operario, Presentismo


class OperarioForm(forms.ModelForm):

    class Meta:
        model = Operario
        fields = [
            'nombre', 'apellido', 'legajo', 'estado', 'categoria', 'telefono', 'imagen', 'obra_actual', 'dni', 'nacimiento', 'empresa'
            ]
        ESTADO_CHOICES = (
            ('Activo', 'Activo'),
            ('Inactivo', 'Inactivo'),
            )
        CATEGORIA_CHOICES = (
            ('Capataz', 'Capataz'),
            ('Especializado', 'Especializado'),
            ('Oficial', 'Oficial'),
            ('Medio Oficial', 'Medio Oficial'),
            ('Ayudante', 'Ayudante'),
            )
        EMPRESA_CHOISES = (
            ('OMSA', 'OMSA'),
            ('CWI', 'CWI'),
        )
        widgets = {
            'legajo': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Legajo', 'type':'number'}),
            'nombre': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}),
            'apellido': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Apellido'}),
            'estado' : forms.Select(choices=ESTADO_CHOICES,attrs={'class': 'form-control'}),
            'categoria' : forms.Select(choices=CATEGORIA_CHOICES,attrs={'class': 'form-control'}),
            'telefono': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Telefono', 'type':'number'}),
            'imagen' : forms.FileInput(attrs={'class':'form-control', 'placeholder': ''}),
            'dni' : forms.NumberInput(attrs={'class':'form-control', 'placeholder':'DNI', 'type':'number'}),
            'nacimiento' : forms.DateInput(format=('%d/%m/%Y'), attrs={'type': 'text', 'class':'form-control myDateClass', 'placeholder':'Fecha de Nacimiento', 'onfocus':"(this.type='date')"}),
            'obra_actual': forms.Select(attrs={'class': 'form-control'}),
            'empresa' : forms.Select(choices=EMPRESA_CHOISES,attrs={'class': 'form-control'}),
        }


class PresentismoForm(forms.ModelForm):

    class Meta:
        model = Presentismo
        fields = [
            'operario', 'obra', 'fecha', 'hora_ingreso', 'hora_egreso', 'actividad', 'observaciones', 'estado', 'cargado'
            ]
        ESTADO_CHOICES = (
            ('Presente', 'Presente'),
            ('Ausente', 'Ausente'),
            ('Vacaciones', 'Vacaciones'),
            ('ART', 'ART'),
        )
        widgets = {
            'operario': forms.Select(attrs={'class': 'form-control'}),
            'obra': forms.Select(attrs={'class': 'form-control'}),
            'fecha': forms.DateInput(format=('%d/%m/%Y'), attrs={'type': 'text', 'class':'form-control myDateClass', 'placeholder':'Fecha montados', 'onfocus':"(this.type='date')"}),
            'hora_ingreso' : forms.DateField(widget=forms.DateInput(attrs={'class':'timepicker'})),
            'hora_egreso' : forms.DateField(widget=forms.DateInput(attrs={'class':'timepicker'})),
            'actividad': forms.Select(attrs={'class': 'form-control'}),
            'observaciones' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'IRPI - IRCO'}),
            'estado' : forms.Select(choices=ESTADO_CHOICES,attrs={'class': 'form-control'}),
        }

omsa-admin/adminomsa/operario/views.py
from django.shortcuts import render
from obra.models import Montaje

from obra.models import Obra
from .models import Operario, Actividad, Presentismo, Dia
from django.views.generic import ListView, DetailView, UpdateView, CreateView, View
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from .forms import OperarioForm
import pandas as pd
from collections import defaultdict
from datetime import datetime, time
from django.shortcuts import get_object_or_404
from django.utils.encoding import uri_to_iri 
 

class StaffRquiredMixin(object):
    """
    Este mixin requerira que el usuario sea miembro del staff
    """
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffRquiredMixin, self).dispatch(request, *args, **kwargs)

# Create your views here.

# ------------------------------------------------------------------------------------------ Operario List

class OperarioListView(ListView):
    model = Operario

# ------------------------------------------------------------------------------------------ Operario Inactivo

class InactivoListView(ListView):
    model = Operario
    template_name = 'operario/operario_inactivo.html'

# ------------------------------------------------------------------------------------------ Operario Create



# ------------------------------------------------------------------------------------------ Operario Detail


class OperarioUpdate(UpdateView):
    model = Operario
    form_class = OperarioForm
    template_name = 'operario/update.html'

    def get_success_url(self):
        return reverse_lazy('operario:operario')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['operario'] = self.model.objects.all()
        return context

# ------------------------------------------------------------------------------------------ Operario Create

class OperarioCreate(CreateView):
    model = Operario
    form_class = OperarioForm
    template_name = 'operario/operario_create.html'

#    fields = ['title', 'content', 'order']
    success_url = reverse_lazy('operario:operario')


# ------------------------------------------------------------------------------------------ Fecha List calendario

class DiaListView(ListView):
    model = Dia
    
    def get_success_url(self):
        return reverse_lazy('operario:operario', args=[self.object.modulo.obra.obra_id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['presentismo'] = Presentismo.objects.all()
        context['actividad'] = Actividad.objects.all()
        context['obra'] = Obra.objects.all()
        context['dias'] = Dia.objects.all()

        prom_carga = []
        prom_pres = []


        for d in Dia.objects.all():
            pers_activo = Presentismo.objects.filter(fecha=d).count()
            present = Presentismo.objects.filter(fecha=d, estado="Presente").count()
            carga = Presentismo.objects.filter(fecha=d, cargado=True).count()
            if carga != 0:
                n = round(carga/pers_activo*100,2)
                prom_carga.append(n)
            else:
                prom_carga.append(0)

            if present != 0:
                n = round(present/pers_activo*100,2)
                prom_pres.append(n)
            else:
                prom_pres.append(0)
        
        prom = zip(Dia.objects.all(), prom_pres, prom_carga)
        context['prom'] = prom

        return context

    def dispatch(self, request, *args, **kwargs):
        dias = Dia.objects.values_list('fecha', flat=True).order_by('fecha')
        dias_list = pd.bdate_range(start=dias[0],end=datetime.today())
        dias_create = []
        for d in dias_list:
            if d.date() not in dias: #si aparece algun error, esta aca
                dias_create.append(d)
        for dc in dias_create:
            Dia.objects.create(fecha=dc, slug=dc.strftime("%y%m%d"))
        for p in Operario.objects.filter(estado="Activo"):
            for dcc in Dia.objects.all():
                if dcc.fecha in dias_create:
                    Presentismo.objects.create(
                        operario=p,
                        obra=p.obra_actual,
                        fecha=dcc,
                        hora_ingreso=time(7, 0),
                        hora_egreso=time(16, 0),
                        actividad_id=1
                    )
        return super().dispatch(request, *args, **kwargs)

# ------------------------------------------------------------------------------------------ Fecha Detail

class DiaUpdate(DetailView):
    model = Dia
    template_name = 'operario/dia_update.html'

    def get_success_url(self):
        return reverse_lazy('operario:fecha')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['presentismo'] = Presentismo.objects.filter(fecha_id=self.object.id)
        context['actividad'] = Actividad.objects.all()
        context['obra'] = Obra.objects.all()
        return context
    
    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            obra_hoy = dict(zip(request.POST.getlist('id'), request.POST.getlist('obra'))) 
            estado = dict(zip(request.POST.getlist('id'), request.POST.getlist('estado')))
            ingreso = dict(zip(request.POST.getlist('id'), request.POST.getlist('hora_ingreso')))
            egreso = dict(zip(request.POST.getlist('id'), request.POST.getlist('hora_egreso')))
            actividad = dict(zip(request.POST.getlist('id'), request.POST.getlist('actividad')))
            observaciones = dict(zip(request.POST.getlist('id'), request.POST.getlist('observaciones')))

            dd = defaultdict(list)
            for d in (obra_hoy, estado, ingreso, egreso, actividad, observaciones): 
                for key, value in d.items():
                    dd[key].append(value)
            
            for key, value in dd.items():
                e = Presentismo.objects.get(id=key)
                if value[0] != "x":
                    e.obra_id = value[0]
                e.estado = value[1]
                e.hora_ingreso = value[2]
                e.hora_egreso = value[3]
                e.actividad_id = value[4]
                if value[5] != "":
                    e.observaciones = value[5]
                e.save()

            id_cargado = request.POST.getlist('cargado')
            print(id_cargado)
            for x in id_cargado:
                Presentismo.objects.filter(id=int(x)).update(cargado=True) 


            return self.get(request, *args, **kwargs)

omsa-admin/adminomsa/operario/templates/operario/dia_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Obras{% endblock %}
{% block content %}
{% include "operario/includes/submenu.html" %}
<link href="{% static 'core/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />

<style>
  .centered {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .m_title:first-letter {
  text-transform: uppercase
}
</style>

{% include "obra/includes/loader_1.html" %}
<div class="col-12">
  <div class="card mb-3">
      <form action="" method=POST>
          {% csrf_token %}
      <div class="card-header">
          <h3 class="card-title">Parte diario</h3>
          <button type="submit" class="btn btn-secondary btn-sm ms-auto m-2" >
            Guardar cambios
        </button>
      </div>
      <div class="table-responsive">
        <table id="example" class="table card-table table-vcenter text-nowrap table-hover datatable" width="100%">
            <thead>
              <tr>
                <th scope="col">Fecha</th>
                <th scope="col">Día</th>
                <th scope="col">% Pres</th>
                <th scope="col">% Carga</th>
                <th scope="col">Estado</th>
                <th scope="col">Cargar</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th scope="col">Fecha</th>
                <th scope="col">Día</th>
                <th scope="col">% Pres</th>
                <th scope="col">% Carga</th>
                <th scope="col">Estado</th>
                <th scope="col">Cargar</th>
            </tr>
          </tfoot>
          <tbody>
            
            
            {% for d, p, c in prom %}
                    <td>{{ d.fecha|date:"Y-m-d" }}</td>
                    <td class="m_title">{{ d.fecha|date:"l" }}</td>
                    <td>{{ p }} %</td>
                    <td>{{ c }} %</td>
                    <td>{% if d.estado %} Lab {% else %} No lab. {% endif %}</td>
                    <td>
                        <a href="{% url 'operario:parte' d.slug %}">Cargar</a>
                      </td>
                </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>
  </div>
</div>



{% include "obra/includes/loader_2.html" %}
{% endblock %}

{% block extrasjs %}
<script src="{% static 'core/js/jquery-1.11.3.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/obra_list.js' %}" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script type="text/javascript">
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>




{% endblock extrasjs %}

omsa-admin/adminomsa/operario/templates/operario/dia_update.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Obras{% endblock %}
{% block content %}
{% include "operario/includes/submenu.html" %}
<link href="{% static 'core/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />

<style>
  .centered {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  </style>

{% include "obra/includes/loader_1.html" %}
<div class="col-12">
  <div class="card mb-3">
      <form action="" method=POST>
          {% csrf_token %}
      <div class="card-header">
          <h3 class="card-title">Parte diario</h3>
          <button type="submit" class="btn btn-secondary btn-sm ms-auto m-2" >
            Guardar cambios
        </button>
      </div>
      <div class="table-responsive">
        <table id="example" class="table card-table table-vcenter text-nowrap table-hover datatable" width="100%">
            <thead>
              <tr>
                <th scope="col">Fecha</th>
                <th scope="col">Nombre</th>
                <th scope="col">Obra base</th>
                <th scope="col">Seleccionar</th>
                <th scope="col">Obra Asignada</th>
                <th scope="col">Estado</th>
                <th scope="col">Ingreso</th>
                <th scope="col">Egreso</th>
                <th scope="col">Actividad</th>
                <th scope="col">Observaciones</th>
                <th scope="col">OK</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th scope="col">Fecha</th>
                <th scope="col">Nombre</th>
                <th scope="col">Obra base</th>
                <th scope="col">Seleccionar</th>
                <th scope="col">Obra Asignada</th>
                <th scope="col">Estado</th>
                <th scope="col">Ingreso</th>
                <th scope="col">Egreso</th>
                <th scope="col">Actividad</th>
                <th scope="col">Observaciones</th>
                <th scope="col">OK</th>
            </tr>
          </tfoot>
          <tbody>
            {% for pres in presentismo|dictsort:'operario.apellido' %}
                <tr>

                  <td type="date">{{pres.fecha.fecha|date:"d/m/Y"}}</td>
                  <td>{{pres.operario}}</td>
                  <td>{{pres.operario.obra_actual}}</td>
                  <td>
                    <input type="hidden" name="id" value="{{pres.id}}">
                    <select class="form-control form-control-sm" style="text-align:center" name="obra">
                          <option value="x">...</option>
                      {% for ob in obra %}
                          <option value='{{ob.id}}'>{{ob.obra}}</option>
                      {% endfor %}
                  </td>
                  <td>{{pres.obra}}</td> 
                  <td>
                    <select class="form-control form-control-sm" style="text-align:center" name="estado">
                      <option></option>
                      {% if pres.estado == "Presente" %}
                        <option selected="selected" value="Presente">Presente</option>
                      {% else %}
                        <option  value="Presente">Presente</option>
                      {% endif %}
                      {% if pres.estado == "Ausente" %}
                        <option selected="selected" value="Ausente">Ausente</option>
                      {% else %}
                        <option  value="Ausente">Ausente</option>
                      {% endif %}
                      {% if pres.estado == "Vacaciones" %}
                        <option selected="selected" value="Vacaciones">Vacaciones</option>
                      {% else %}
                        <option  value="Vacaciones">Vacaciones</option>
                      {% endif %}
                      {% if pres.estado == "ART" %}
                        <option selected="selected" value="ART">ART</option>
                      {% else %}
                        <option  value="ART">ART</option>
                      {% endif %}
                  </td>                 
                  <td>
                    <input class="form-control form-control-sm" type="time" value="{{pres.hora_ingreso}}" style="text-align:center" name="hora_ingreso">
                  </td>
                  <td>
                    <input class="form-control form-control-sm" type="time" value="{{pres.hora_egreso}}" style="text-align:center" name="hora_egreso">
                  </td>
                  <td>
                    <select class="form-control form-control-sm" placeholder="{{pres.operario.actividad}}" style="text-align:center" name="actividad">
                      {% for act in actividad %} 
                        {% if act.id == pres.actividad_id  %}
                          <option selected value='{{act.id}}' > {{act.id_tarea}} </option> 
                        {% else %}
                        <option value='{{act.id}}' > {{act.id_tarea}} </option>
                        {% endif %}
                      {% endfor %}
                  </td>  
                  <td>
                    {% if pres.observaciones == NULL %}
                      <input class="form-control form-control-sm" type="text" placeholder="" style="text-align:center" name="observaciones">
                    {% else %}
                      <input class="form-control form-control-sm" type="text" placeholder="{{pres.observaciones}}" style="text-align:center" name="observaciones">
                    {% endif %}
                  </td>
                  <td>
                    {% if pres.cargado %} 
                        <div class="form-check centered">
                            <input class="form-check-input" type="checkbox" checked="checked" value={{pres.operario.id}} name="cargado" disabled>
                        </div>
                    {% else %}
                        <div class="form-check centered">
                            <input class="form-check-input" type="checkbox" value={{pres.id}} name="cargado">
                        </div>
                    {% endif %}
                </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
</div>



{% include "obra/includes/loader_2.html" %}
{% endblock %}

{% block extrasjs %}
<script src="{% static 'core/js/jquery-1.11.3.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/obra_list.js' %}" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script type="text/javascript">
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>




{% endblock extrasjs %}

omsa-admin/adminomsa/operario/templates/operario/operario_inactivo.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Obras{% endblock %}
{% block content %}
{% include "operario/includes/submenu.html" %}
<link href="{% static 'core/css/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />


{% include "obra/includes/loader_1.html" %}
    <div class="col-12">
      <div class="card mb-3 mt-3">
        <div class="card-header">
          <h3 class="card-title">Listado de personal activo</h3>
        </div>
        <div class="table-responsive">
          <table id="example" class="table card-table table-vcenter text-nowrap table-hover datatable" width="100%">
            <thead>
              <tr>
                <th>Legajo</th>
                <th>Apellido</th>
                <th>Nombre</th>
                <th>Categoria</th>
                <th>Obra</th>
                <th>Ficha</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Legajo</th>
                <th>Apellido</th>
                <th>Nombre</th>
                <th>Categoria</th>
                <th>Obra</th>
                <th>Ficha</th>
              </tr>
            </tfoot>
            <tbody>
              {% for operario in object_list|dictsort:'legajo' %}
               {% if operario.estado == 'Inactivo' %}
                  <tr>
                    <td>{{operario.legajo}}</td>                                
                    <td>{{operario.apellido}}</td>
                    <td>{{operario.nombre}}</td>
                    <td>{{operario.categoria}}</td>
                    <td>{{operario.obra_actual.obra}}</td>
                    <td>
                      <a href="{% url 'operario:update' operario.legajo %}">Ver</a>
                    </td>
                  </tr>
                {% endif %}
              {% endfor %}
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>  




{% include "obra/includes/loader_2.html" %}
{% endblock %}

{% block extrasjs %}
<script src="{% static 'core/js/jquery-1.11.3.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'core/js/obra_list.js' %}" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" type="text/javascript"></script>


{% endblock extrasjs %}


<!--  
href 
{% url 'obras:obra' obra.obra_id obra.obra|slugify %}
-->